In [96]:
import pandas as pd

ztf_data = pd.read_pickle('data/ztf/lc_from_first_mjd_forced_fot.pkl')
ztf_data

oid           mjd          ra        dec  fid  flux_tot_ujy  \
91      ZTF18aaaqexr  58886.439456  175.776546  15.567160    1    733.608232   
92      ZTF18aaaqexr  58891.320255  175.776546  15.567160    2   1504.452801   
93      ZTF18aaaqexr  58891.420880  175.776546  15.567160    1    796.023260   
94      ZTF18aaaqexr  58894.353704  175.776546  15.567160    1    772.638964   
95      ZTF18aaaqexr  58894.468345  175.776546  15.567160    2   1487.203851   
...              ...           ...         ...        ...  ...           ...   
917930  ZTF21abidtrd  59405.317500  283.249749  28.959674    1    506.245423   
917931  ZTF21abidtrd  59407.281354  283.249749  28.959674    1    487.892594   
917932  ZTF21abidtrd  59407.317176  283.249749  28.959674    2    870.134863   
917933  ZTF21abidtrd  59409.296111  283.249749  28.959674    2    862.413520   
917934  ZTF21abidtrd  59409.333646  283.249749  28.959674    1    479.596502   

        fluxunc_tot_ujy_resc alerceclass  
91                  7.126595        SNIa  
92                 10.895416        SNIa  
93                 10.651924        SNIa  
94                  4.406099        SNIa  
95                  4.759942        SNIa  
...                      ...         ...  
917930              8.319171        SNIa  
917931              8.267767        SNIa  
917932              9.425640        SNIa  
917933              9.234165        SNIa  
917934              9.483954        SNIa  

[493777 rows x 8 columns]

In [97]:
ztf_data.fid.unique()

array([1, 2, 3], dtype=int64)

In [98]:
bands = [1, 2]
bands

[1, 2]

In [99]:
ztf_data[ztf_data.fid.isin(bands)]

oid           mjd          ra        dec  fid  flux_tot_ujy  \
91      ZTF18aaaqexr  58886.439456  175.776546  15.567160    1    733.608232   
92      ZTF18aaaqexr  58891.320255  175.776546  15.567160    2   1504.452801   
93      ZTF18aaaqexr  58891.420880  175.776546  15.567160    1    796.023260   
94      ZTF18aaaqexr  58894.353704  175.776546  15.567160    1    772.638964   
95      ZTF18aaaqexr  58894.468345  175.776546  15.567160    2   1487.203851   
...              ...           ...         ...        ...  ...           ...   
917930  ZTF21abidtrd  59405.317500  283.249749  28.959674    1    506.245423   
917931  ZTF21abidtrd  59407.281354  283.249749  28.959674    1    487.892594   
917932  ZTF21abidtrd  59407.317176  283.249749  28.959674    2    870.134863   
917933  ZTF21abidtrd  59409.296111  283.249749  28.959674    2    862.413520   
917934  ZTF21abidtrd  59409.333646  283.249749  28.959674    1    479.596502   

        fluxunc_tot_ujy_resc alerceclass  
91                  7.126595        SNIa  
92                 10.895416        SNIa  
93                 10.651924        SNIa  
94                  4.406099        SNIa  
95                  4.759942        SNIa  
...                      ...         ...  
917930              8.319171        SNIa  
917931              8.267767        SNIa  
917932              9.425640        SNIa  
917933              9.234165        SNIa  
917934              9.483954        SNIa  

[485965 rows x 8 columns]

In [ ]:
ztf_data[ztf_data.fid != 'i']

In [13]:
bands_name = ['g', 'r']
bands_name

['g', 'r']

In [11]:
lista = [True, False, True]
lista

[True, False, True]

In [16]:
tot = []
tot

[]

In [17]:
tot.append([])
tot

[[]]

In [18]:
tot.append([])
tot

[[], []]

In [21]:
len(tot[1])

0

In [1]:
import random

t = []
g_temp_arr = []
r_temp_arr = []
g_err_temp_arr = []
r_err_temp_arr = []

for i in range(6):
    t.append(random.randint(1,50))
    g_temp_arr.append(random.randint(1,50))
    r_temp_arr.append(random.randint(1,50))
    g_err_temp_arr.append(random.randint(1,50))
    r_err_temp_arr.append(random.randint(1,50))

In [2]:
print(f"t: {t}")
print(f"g_temp_arr: {g_temp_arr}")
print(f"r_temp_arr: {r_temp_arr}")
print(f"g_err_temp_arr: {g_err_temp_arr}")
print(f"r_err_temp_arr: {r_err_temp_arr}")

t: [34, 37, 44, 22, 33, 15]
g_temp_arr: [4, 37, 47, 2, 15, 50]
r_temp_arr: [43, 24, 16, 37, 50, 21]
g_err_temp_arr: [20, 15, 28, 10, 14, 38]
r_err_temp_arr: [15, 29, 4, 45, 33, 8]


In [7]:
t

[34, 37, 44, 22, 33, 15]

In [8]:
band_arr = [g_temp_arr]+ [r_temp_arr]
band_arr_err = [g_err_temp_arr]+ [r_err_temp_arr]

print(f"band_arr: {band_arr}")
print(f"band_arr_err: {band_arr_err}")

band_arr: [[4, 37, 47, 2, 15, 50], [43, 24, 16, 37, 50, 21]]
band_arr_err: [[20, 15, 28, 10, 14, 38], [15, 29, 4, 45, 33, 8]]


In [9]:
obs = []
for i in range(len(t)):
    aux = []
    aux.append(t[i])
    for idx_band in range(2):
        aux.append(band_arr[idx_band][i])
        aux.append(band_arr_err[idx_band][i])
    obs.append(aux)

obs

[[34, 4, 20, 43, 15],
 [37, 37, 15, 24, 29],
 [44, 47, 28, 16, 4],
 [22, 2, 10, 37, 45],
 [33, 15, 14, 50, 33],
 [15, 50, 38, 21, 8]]

In [4]:
obs = [[t[i], g_temp_arr[i], r_temp_arr[i], g_err_temp_arr[i], r_err_temp_arr[i]] for i in range(len(t))]
obs

[[34, 4, 43, 20, 15],
 [37, 37, 24, 15, 29],
 [44, 47, 16, 28, 4],
 [22, 2, 37, 10, 45],
 [33, 15, 50, 14, 33],
 [15, 50, 21, 38, 8]]

In [76]:
import random

t = []
band_temp_arr = []
band_err_temp_arr = []

for idx_band in range(2):
    band_temp_arr.append([])
    band_err_temp_arr.append([])


for j in range(2):
    for i in range(6):
        if j == 0: t.append(random.randint(1,50))
        band_temp_arr[j].append(random.randint(1,50))
        band_err_temp_arr[j].append(random.randint(1,50))

In [77]:
print(f"t: {t}")
print(f"band_temp_arr: {band_temp_arr}")
print(f"band_err_temp_arr: {band_err_temp_arr}")

t: [9, 1, 45, 49, 5, 46]
band_temp_arr: [[38, 43, 30, 8, 37, 13], [17, 42, 14, 46, 37, 12]]
band_err_temp_arr: [[11, 45, 12, 1, 35, 38], [17, 9, 2, 36, 21, 6]]


In [79]:
obs = [t] + band_temp_arr + band_err_temp_arr
obs

[[9, 1, 45, 49, 5, 46],
 [38, 43, 30, 8, 37, 13],
 [17, 42, 14, 46, 37, 12],
 [11, 45, 12, 1, 35, 38],
 [17, 9, 2, 36, 21, 6]]

In [85]:
obs[1:5]

[[38, 43, 30, 8, 37, 13],
 [17, 42, 14, 46, 37, 12],
 [11, 45, 12, 1, 35, 38],
 [17, 9, 2, 36, 21, 6]]

In [87]:
obs[1:len(obs)]

[[38, 43, 30, 8, 37, 13],
 [17, 42, 14, 46, 37, 12],
 [11, 45, 12, 1, 35, 38],
 [17, 9, 2, 36, 21, 6]]

In [82]:
len(obs)

5

In [84]:
length = len(obs)
obs[1:length]

[[38, 43, 30, 8, 37, 13],
 [17, 42, 14, 46, 37, 12],
 [11, 45, 12, 1, 35, 38],
 [17, 9, 2, 36, 21, 6]]

In [31]:
import copy
def prueba(lista):
    lista.append(3)
    lista.append(4)
    lista_1 = lista.copy()
    lista_1 = lista_1 + [34]

    return lista_1

In [32]:
lista_prueba = []
ojito = prueba(lista_prueba)
ojito

[3, 4, 34]

In [33]:
lista_prueba

[3, 4]

In [12]:
import math

tot = []
tot.append(math.prod(lista))
tot

[0]

In [13]:
if all(tot):
    print("HOLY")

In [4]:
import numpy as np
np.zeros(len(bands)) = -999

SyntaxError: cannot assign to function call (Temp/ipykernel_16184/1476790445.py, line 2)

In [5]:
np.full(len(bands), -999)

array([-999, -999])

In [ ]:
g = r = -999 
g_error = r_error = -999

In [8]:
obs = [[1,5,9,67,9], [7,87,4,327,2], [3,6,8,654,4]]
obs

[[1, 5, 9, 67, 9], [7, 87, 4, 327, 2], [3, 6, 8, 654, 4]]

In [9]:
[obs[i][0] for i in range(len(obs))]

[1, 7, 3]

In [10]:
bands = np.full((2), -999, dtype=float)
bands_err = np.full((2), -999, dtype=float)
bands

array([-999., -999.])

In [14]:
bands_arr = []
bands_error_arr = []

for idx_band in range(2):
    bands_arr.append([obs[i][idx_band+1] for i in range(len(obs))])
    bands_error_arr.append([obs[i][idx_band+1+len(bands_name)] for i in range(len(obs))])

bands_arr

[[5, 87, 6], [9, 4, 8]]

In [15]:
bands_error_arr

[[67, 327, 654], [9, 2, 4]]

In [4]:
import torch

In [5]:
m = torch.nn.LogSoftmax(dim=1)
loss = torch.nn.NLLLoss()
# input is of size N x C = 3 x 5
input = torch.randn(3, 5, requires_grad=True)
# each element in target has to have 0 <= value < C
target = torch.tensor([1, 0, 4])
output = loss(m(input), target)
output.backward()

In [7]:
# 2D loss example (used, for example, with image inputs)
N, C = 5, 4
loss = torch.nn.NLLLoss()
# input is of size N x C x height x width
data = torch.randn(N, 16, 10, 10)
conv = torch.nn.Conv2d(16, C, (3, 3))
m = torch.nn.LogSoftmax(dim=1)
# each element in target has to have 0 <= value < C
target = torch.empty(N, 8, 8, dtype=torch.long).random_(0, C)
output = loss(m(conv(data)), target)
output.backward()

In [11]:
m(conv(data)).size()

torch.Size([5, 4, 8, 8])

In [17]:
torch.nn.functional.log_softmax(torch.rand(3,5, requires_grad=True), dim=1)

tensor([[-1.5050, -1.6025, -1.9498, -1.4743, -1.5831],
        [-1.5557, -1.9238, -1.1835, -1.7494, -1.8152],
        [-1.5943, -1.7358, -1.9226, -1.8609, -1.1428]],
       grad_fn=<LogSoftmaxBackward0>)

In [8]:
import torch
lista = [torch.tensor([1, 0, 0, 0, 1, 0, 1, 1, 0, 1]).to('cuda'), torch.tensor([0, 0, 0, 0, 1, 0, 1, 0, 0, 0]).to('cuda'), torch.tensor([0, 1, 1, 1, 1, 0, 0, 0, 1, 1]).to('cuda')]
lista

[tensor([1, 0, 0, 0, 1, 0, 1, 1, 0, 1], device='cuda:0'),
 tensor([0, 0, 0, 0, 1, 0, 1, 0, 0, 0], device='cuda:0'),
 tensor([0, 1, 1, 1, 1, 0, 0, 0, 1, 1], device='cuda:0')]

In [9]:
torch.cat((lista),dim=0).cpu().numpy()

array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1], dtype=int64)

In [228]:
class MyData(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

#def collate_fn(data):
#    data.sort(key=lambda x: len(x), reverse=True)
#    data = pad_sequence(data, batch_first=True, padding_value=0)
#    return data

def collate_fn(data):
    data.sort(key=lambda x: len(x), reverse=True)
    seq_len = [s.size(0) for s in data]
    
    data = pad_sequence(data, batch_first=True).float() 
    print(f"data: {data}")

    data = data.unsqueeze(-1)
    print(f"data unsqueeze: {data}")

    data = pack_padded_sequence(data, seq_len, batch_first=True)
    return data

a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7])
c = torch.tensor([7,8])
d = torch.tensor([9])
train_x = [a, b, c, d]

In [229]:
data = MyData(train_x)
data_loader = DataLoader(data, batch_size=2, shuffle=True, collate_fn=collate_fn)

In [230]:
batch_x = iter(data_loader).next()
batch_x

data: tensor([[1., 2., 3., 4.],
        [9., 0., 0., 0.]])
data unsqueeze: tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[9.],
         [0.],
         [0.],
         [0.]]])


PackedSequence(data=tensor([[1.],
        [9.],
        [2.],
        [3.],
        [4.]]), batch_sizes=tensor([2, 1, 1, 1]), sorted_indices=None, unsorted_indices=None)

In [236]:
print(batch_x.data.size())
batch_x.data

torch.Size([5, 1])


tensor([[1.],
        [9.],
        [2.],
        [3.],
        [4.]])

In [232]:
rnn = nn.RNN(input_size=1, hidden_size=4, num_layers=1, batch_first=True)
rnn

RNN(1, 4, batch_first=True)

In [235]:
h0 = torch.rand(1, 2, 4).float()
print(h0.size())
h0

torch.Size([1, 2, 4])


tensor([[[0.7152, 0.1443, 0.1762, 0.5152],
         [0.6478, 0.8451, 0.1993, 0.9277]]])

In [237]:
out, h1 = rnn(batch_x, h0)
out

PackedSequence(data=tensor([[-0.1387,  0.8321, -0.3218,  0.9018],
        [ 0.8790,  0.9997, -0.2100,  0.9993],
        [ 0.4744,  0.8615, -0.3654,  0.9228],
        [ 0.4153,  0.9606, -0.3229,  0.9731],
        [ 0.5730,  0.9813, -0.3105,  0.9845]], grad_fn=<CatBackward0>), batch_sizes=tensor([2, 1, 1, 1]), sorted_indices=None, unsorted_indices=None)

In [238]:
out_pad, out_len = pad_packed_sequence(out, batch_first=True)
out_pad

tensor([[[-0.1387,  0.8321, -0.3218,  0.9018],
         [ 0.4744,  0.8615, -0.3654,  0.9228],
         [ 0.4153,  0.9606, -0.3229,  0.9731],
         [ 0.5730,  0.9813, -0.3105,  0.9845]],

        [[ 0.8790,  0.9997, -0.2100,  0.9993],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000,  0.0000]]], grad_fn=<TransposeBackward0>)

In [239]:
out_len

tensor([4, 1])

In [28]:
vector_large = torch.randn(6, 8)
vector_large

tensor([[-1.3377,  0.6104, -0.2931,  0.4540, -0.3063,  0.9195,  0.8094,  0.0117],
        [-0.5594,  1.6916,  0.8256, -1.5459,  1.3003,  0.1594, -0.0759,  0.5071],
        [-0.3560,  0.8762,  0.1942, -0.2805, -0.0241, -1.4893, -0.6983, -1.4939],
        [-0.4580, -1.1823,  0.4549, -0.0122, -0.0450, -0.7694,  0.6710,  0.0550],
        [-0.9885, -0.5520,  1.7361, -0.8071,  0.6708, -0.6326,  0.1010, -0.9185],
        [-0.4420, -0.1469, -0.4238, -0.8563, -0.1200,  1.7409, -0.2473,  1.3851]])

In [29]:
vector_normal = torch.randn(3, 8)
vector_normal

tensor([[ 9.7512e-01, -1.5158e-01, -6.7957e-01, -9.4990e-01,  2.5984e+00,
          9.2269e-01, -9.6934e-01,  1.4508e+00],
        [-1.0017e+00,  4.9982e-02, -2.0450e+00,  1.4372e-01, -5.7959e-01,
         -9.9337e-01,  1.5771e-01,  2.7913e-01],
        [-1.7352e-03, -4.6116e-01,  2.3124e-01,  1.5909e+00, -1.2297e+00,
         -5.5109e-02,  1.4122e+00, -1.4810e+00]])

In [30]:
vector_large.shape[0]-vector_normal.shape[0]

3

In [31]:
torch.nn.functional.pad(vector_normal, (vector_large.shape[0]-vector_normal.shape[0], 0))

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  9.7512e-01, -1.5158e-01,
         -6.7957e-01, -9.4990e-01,  2.5984e+00,  9.2269e-01, -9.6934e-01,
          1.4508e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -1.0017e+00,  4.9982e-02,
         -2.0450e+00,  1.4372e-01, -5.7959e-01, -9.9337e-01,  1.5771e-01,
          2.7913e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, -1.7352e-03, -4.6116e-01,
          2.3124e-01,  1.5909e+00, -1.2297e+00, -5.5109e-02,  1.4122e+00,
         -1.4810e+00]])

In [32]:
torch.nn.functional.pad(vector_normal, (8, 0))

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00,  9.7512e-01, -1.5158e-01,
         -6.7957e-01, -9.4990e-01,  2.5984e+00,  9.2269e-01, -9.6934e-01,
          1.4508e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00, -1.0017e+00,  4.9982e-02,
         -2.0450e+00,  1.4372e-01, -5.7959e-01, -9.9337e-01,  1.5771e-01,
          2.7913e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,
          0.0000e+00,  0.0000e+00,  0.0000e+00, -1.7352e-03, -4.6116e-01,
          2.3124e-01,  1.5909e+00, -1.2297e+00, -5.5109e-02,  1.4122e+00,
         -1.4810e+00]])

In [33]:
result = torch.nn.utils.rnn.pad_sequence([vector_large, vector_normal], batch_first=True, padding_value=0.0)
result

tensor([[[-1.3377e+00,  6.1037e-01, -2.9312e-01,  4.5401e-01, -3.0630e-01,
           9.1946e-01,  8.0943e-01,  1.1676e-02],
         [-5.5942e-01,  1.6916e+00,  8.2563e-01, -1.5459e+00,  1.3003e+00,
           1.5939e-01, -7.5907e-02,  5.0711e-01],
         [-3.5603e-01,  8.7622e-01,  1.9418e-01, -2.8051e-01, -2.4069e-02,
          -1.4893e+00, -6.9832e-01, -1.4939e+00],
         [-4.5797e-01, -1.1823e+00,  4.5491e-01, -1.2174e-02, -4.5019e-02,
          -7.6943e-01,  6.7103e-01,  5.5011e-02],
         [-9.8851e-01, -5.5203e-01,  1.7361e+00, -8.0710e-01,  6.7082e-01,
          -6.3264e-01,  1.0104e-01, -9.1846e-01],
         [-4.4203e-01, -1.4694e-01, -4.2381e-01, -8.5629e-01, -1.1998e-01,
           1.7409e+00, -2.4732e-01,  1.3851e+00]],

        [[ 9.7512e-01, -1.5158e-01, -6.7957e-01, -9.4990e-01,  2.5984e+00,
           9.2269e-01, -9.6934e-01,  1.4508e+00],
         [-1.0017e+00,  4.9982e-02, -2.0450e+00,  1.4372e-01, -5.7959e-01,
          -9.9337e-01,  1.5771e-01,  2.7913e-01]

In [44]:
vector_large.shape

torch.Size([6, 8])

In [41]:
vector_large.size(1)

8

In [35]:
x_packed = torch.nn.utils.rnn.pack_padded_sequence(vector_normal, vector_large.shape, batch_first=True, enforce_sorted=False)
x_packed

PackedSequence(data=tensor([-1.0017,  0.9751,  0.0500, -0.1516, -2.0450, -0.6796,  0.1437, -0.9499,
        -0.5796,  2.5984, -0.9934,  0.9227,  0.1577,  0.2791]), batch_sizes=tensor([2, 2, 2, 2, 2, 2, 1, 1]), sorted_indices=tensor([1, 0]), unsorted_indices=tensor([1, 0]))

In [5]:
import torch

a = torch.tensor([[0, 0, 0, 0]])

padding = torch.cat((a, x), 0)
padding

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000],
        [-0.0032, -0.9792,  1.1070,  1.0795],
        [ 0.3225,  0.4289, -1.3852, -0.2841],
        [ 1.0932, -0.8647,  0.8619, -0.2636]])

In [7]:
mask = padding.ge(0.0)
mask

tensor([[ True,  True,  True,  True],
        [False, False,  True,  True],
        [ True,  True, False, False],
        [ True, False,  True, False]])

In [ ]:
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)

In [133]:
import torch
import torch.nn as nn
from torch.autograd import Variable

batch_size = 3
max_length = 3
hidden_size = 2
n_layers = 1

# container
batch_in = torch.zeros((batch_size, 1, max_length))
batch_in

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]])

In [134]:
#data
vec_1 = torch.FloatTensor([[1, 2, 3]])
vec_2 = torch.FloatTensor([[1, 2, 0]])
vec_3 = torch.FloatTensor([[1, 0, 0]])

batch_in[0] = vec_1
batch_in[1] = vec_2
batch_in[2] = vec_3
batch_in

tensor([[[1., 2., 3.]],

        [[1., 2., 0.]],

        [[1., 0., 0.]]])

In [135]:
batch_in.requires_grad_()

tensor([[[1., 2., 3.]],

        [[1., 2., 0.]],

        [[1., 0., 0.]]], requires_grad=True)

In [136]:
batch_in.size()

torch.Size([3, 1, 3])

In [137]:
seq_lengths = [3,2,1]

In [138]:
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)
pack

PackedSequence(data=tensor([[1., 2., 3.],
        [1., 2., 0.],
        [1., 0., 0.]], grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [141]:
# initialize
## (batch_size=N, sequence_length=L, input_size=H_in)
# rnn = nn.RNN(max_length, hidden_size, n_layers, batch_first=True) 
rnn = nn.RNN(input_size=batch_in.size(0), hidden_size=hidden_size, num_layers=n_layers, batch_first=True) 
rnn

RNN(3, 2, batch_first=True)

In [142]:
# (D∗num_layers, N, H_out)
h0 = torch.randn((n_layers, batch_size, hidden_size), requires_grad=True)
h0

tensor([[[ 1.4801, -0.0870],
         [ 0.2476, -0.2566],
         [ 0.2596, -2.1887]]], requires_grad=True)

In [143]:
h0.size()

torch.Size([1, 3, 2])

In [144]:
pack

PackedSequence(data=tensor([[1., 2., 3.],
        [1., 2., 0.],
        [1., 0., 0.]], grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [150]:
pack.data

tensor([[1., 2., 3.],
        [1., 2., 0.],
        [1., 0., 0.]], grad_fn=<PackPaddedSequenceBackward0>)

In [153]:
pack.data

tensor([[1., 2., 3.],
        [1., 2., 0.],
        [1., 0., 0.]], grad_fn=<PackPaddedSequenceBackward0>)

In [156]:
#forward 
out, _ = rnn(pack, h0)
out

RuntimeError: start (3) + length (2) exceeds dimension size (3).

In [125]:
rnn = nn.RNN(10, 20, 2)
rnn

RNN(10, 20, num_layers=2)

In [92]:
a = torch.Tensor([[1], [2], [3]])
b = torch.Tensor([[4], [5]])
c = torch.Tensor([[6]])
packed = torch.nn.utils.rnn.pack_sequence([a, b, c])
packed


PackedSequence(data=tensor([[1.],
        [4.],
        [6.],
        [2.],
        [5.],
        [3.]]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [93]:
lstm = nn.LSTM(1,3)
lstm

LSTM(1, 3)

In [94]:
packed_output, (h,c) = lstm(packed)
packed_output

PackedSequence(data=tensor([[-0.0659, -0.0926, -0.1677],
        [-0.1125, -0.0323,  0.2522],
        [-0.0634, -0.0132,  0.4770],
        [-0.1451, -0.1283, -0.2020],
        [-0.1288, -0.0313,  0.5098],
        [-0.1826, -0.1290, -0.0847]], grad_fn=<CatBackward0>), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [95]:
(h,c)

(tensor([[[-0.1826, -0.1290, -0.0847],
          [-0.1288, -0.0313,  0.5098],
          [-0.0634, -0.0132,  0.4770]]], grad_fn=<StackBackward0>),
 tensor([[[-0.8498, -0.3826, -0.1405],
          [-1.3391, -0.2029,  0.9316],
          [-0.8320, -0.1094,  0.7377]]], grad_fn=<StackBackward0>))

In [96]:
y = torch.nn.utils.rnn.pad_packed_sequence(packed_output)
y

(tensor([[[-0.0659, -0.0926, -0.1677],
          [-0.1125, -0.0323,  0.2522],
          [-0.0634, -0.0132,  0.4770]],
 
         [[-0.1451, -0.1283, -0.2020],
          [-0.1288, -0.0313,  0.5098],
          [ 0.0000,  0.0000,  0.0000]],
 
         [[-0.1826, -0.1290, -0.0847],
          [ 0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000]]], grad_fn=<CopySlices>),
 tensor([3, 2, 1]))

RuntimeError: start (3) + length (2) exceeds dimension size (3).

In [86]:
#forward 
out, _ = rnn(pack, h0)
out

RuntimeError: start (3) + length (2) exceeds dimension size (3).

In [ ]:
# batch_size = 3
# max_length = 3
# hidden_size = 2
# n_layers =1
_

In [56]:
# unpack
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out)
unpacked

AttributeError: 'Tensor' object has no attribute 'batch_sizes'

In [57]:
unpacked_len

NameError: name 'unpacked_len' is not defined

In [157]:
batch_size = 4
max_length = 3
hidden_size = 2
n_layers =1
feature_dim = 1

In [161]:
# container
#batch_in = torch.zeros((batch_size, max_length, feature_dim)) # 2
batch_in = torch.zeros((batch_size, 1, max_length)) # 1
batch_in

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]],

        [[0., 0., 0.]]])

In [163]:
# data
vec_1 = torch.FloatTensor([[1, 2, 3]])
vec_2 = torch.FloatTensor([[1, 2, 0]])
vec_3 = torch.FloatTensor([[1, 0, 0]])
vec_4 = torch.FloatTensor([[2, 0, 0]])

batch_in[0] = vec_1
batch_in[1] = vec_2
batch_in[2] = vec_3
batch_in[3] = vec_4

#batch_in = Variable(batch_in)
batch_in.requires_grad_()
batch_in

tensor([[[1., 2., 3.]],

        [[1., 2., 0.]],

        [[1., 0., 0.]],

        [[2., 0., 0.]]], requires_grad=True)

In [164]:
print(batch_in.size())
seq_lengths = [3,2,1,1] # list of integers holding information about the batch size at each sequence step

torch.Size([4, 1, 3])


In [165]:
# pack it
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)
print(pack)

PackedSequence(data=tensor([[1., 2., 3.],
        [1., 2., 0.],
        [1., 0., 0.],
        [2., 0., 0.]], grad_fn=<PackPaddedSequenceBackward0>), batch_sizes=tensor([4, 2, 1]), sorted_indices=None, unsorted_indices=None)


In [167]:
# initialize
rnn = nn.RNN(batch_in.size(0), hidden_size, n_layers, batch_first=True)
rnn

RNN(4, 2, batch_first=True)

In [168]:
h0 = torch.randn((n_layers, batch_size, hidden_size), requires_grad=True)
h0

tensor([[[-1.7133, -1.1805],
         [-0.7070,  0.4656],
         [ 0.3746,  0.6887],
         [-0.8825, -0.5778]]], requires_grad=True)

In [169]:
#forward 
out, _ = rnn(pack, h0)
out

RuntimeError: input.size(-1) must be equal to input_size. Expected 4, got 3

In [ ]:


# unpack
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out, batch_first=True)
print(unpacked)

In [176]:
batch_size = 4
max_length = 3
hidden_size = 2
n_layers =1
feature_dim = 1

# container
batch_in = torch.zeros((batch_size, max_length, feature_dim))

# data
vec_1 = torch.FloatTensor([[[1], [2], [3]]])
vec_2 = torch.FloatTensor([[[1], [2], [0]]])
vec_3 = torch.FloatTensor([[[1], [0], [0]]])
vec_4 = torch.FloatTensor([[[2], [0], [0]]])

batch_in[0] = vec_1
batch_in[1] = vec_2
batch_in[2] = vec_3
batch_in[3] = vec_4
print(batch_in.size())
batch_in

torch.Size([4, 3, 1])


tensor([[[1.],
         [2.],
         [3.]],

        [[1.],
         [2.],
         [0.]],

        [[1.],
         [0.],
         [0.]],

        [[2.],
         [0.],
         [0.]]])

In [177]:
seq_lengths = [3,2,1,1] # list of integers holding information about the batch size at each sequence step

# pack it
pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)
print(pack)

PackedSequence(data=tensor([[1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [3.]]), batch_sizes=tensor([4, 2, 1]), sorted_indices=None, unsorted_indices=None)


In [179]:
pack.data.size()
pack.data

tensor([[1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [3.]])

In [ ]:
rnn = nn.RNN(feature_dim, hidden_size, n_layers, batch_first=True) 
h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))

In [ ]:
#forward 
out, _ = rnn(pack, h0)

# unpack
unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out, batch_first=True)
print(unpacked)

In [3]:
len([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,  9,  9,  9,  9,  9,  9,  9,
         9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  8,  7,  7,  6,  5,  5,  5,  4,
         4,  4,  4,  3,  2,  2,  2,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  1,  1,  1,  1])

59

In [3]:
import torch
torch.tensor([61, 40, 39, 39, 37, 33, 28, 18, 17, 14]).unsqueeze(-1)

tensor([[61],
        [40],
        [39],
        [39],
        [37],
        [33],
        [28],
        [18],
        [17],
        [14]])

In [11]:
unpacked = torch.tensor([[[ 1.6538e-02,  5.6767e-02,  9.0571e-04,  3.0647e-02,
          -4.7211e-02,  7.6125e-02],
         [ 1.3896e-02,  1.6257e-02, -1.6220e-02, -1.2280e-02,
           8.3733e-03, -2.7838e-02],
         [ 2.5685e-02,  3.3586e-02,  1.8123e-02,  2.4158e-02,
           9.5614e-03,  3.1805e-02],
         [-2.0610e-01, -7.0265e-02,  5.8711e-02, -4.2112e-03,
           1.3706e-01, -3.6016e-02],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02]],

        [[-5.6594e-02,  1.6429e-02,  5.9902e-02,  3.7806e-02,
           4.3941e-02,  9.6136e-02],
         [-9.4041e-02, -1.6179e-02,  6.4783e-02, -3.0855e-02,
           1.5764e-01, -2.1854e-02],
         [-6.4557e-02, -6.2401e-02,  4.2734e-03,  1.1267e-01,
           2.3573e-01,  6.0810e-02],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],           
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]],

        [[ 3.0731e-02,  3.4918e-02, -2.5661e-02,  7.8089e-02,
          -1.3263e-01,  8.3883e-02],
         [-4.1114e-02, -4.4349e-02, -4.6148e-02,  1.4719e-01,
          -1.7767e-01,  1.1240e-01],
         [-4.8966e-02, -3.3305e-02, -1.9329e-02,  1.5953e-01,
           6.3815e-03,  1.4913e-01],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]],


        [[ 2.6054e-02, -1.0205e-02,  4.3393e-02, -3.8335e-02,
          -1.1724e-02, -2.7068e-02],
         [ 3.2665e-02, -1.0081e-02,  1.0885e-01,  1.2793e-01,
           1.4153e-01,  4.8708e-02],
         [ 5.3791e-02, -3.3659e-02,  1.2479e-01,  1.3702e-01,
           1.4016e-01,  3.7281e-02],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]],

        [[ 3.5541e-03, -3.1010e-02, -4.0462e-02,  6.6716e-02,
          -6.9438e-02,  4.3141e-02],
         [ 1.4525e-02, -7.0359e-03, -3.1221e-03,  4.9759e-02,
          -1.3915e-02,  9.0185e-02],
         [ 5.9673e-04, -7.5668e-02, -1.3084e-04,  2.7947e-02,
           8.1181e-02,  3.9457e-02],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]],

        [[-9.3490e-02, -3.7732e-02,  2.2119e-02,  8.1481e-02,
          -2.6966e-02,  5.9264e-02],
         [-1.8529e-01, -5.4526e-02,  3.7262e-02,  4.2626e-02,
           1.5307e-01,  9.5252e-02],
         [-2.7138e-01, -7.4981e-02,  1.0714e-01, -3.7837e-02,
           1.7267e-01,  1.5304e-01],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-2.3777e-01, -5.7890e-02,  8.9409e-02,  5.7700e-03,
           1.8906e-01,  4.9379e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]],
          
         [[-9.3490e-02, -3.7732e-02,  2.2119e-02,  8.1481e-02,
          -2.6966e-02,  5.9264e-02],
         [-1.8529e-01, -5.4526e-02,  3.7262e-02,  4.2626e-02,
           1.5307e-01,  9.5252e-02],
         [-2.7138e-01, -7.4981e-02,  1.0714e-01, -3.7837e-02,
           1.7267e-01,  1.5304e-01],
         [-1.4957e-01,  1.4763e-02,  5.0862e-02,  2.8549e-02,
           1.6792e-01,  3.1487e-02],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00],
         [-1.0000e+00, -1.0000e+00, -1.0000e+00, -1.0000e+00,
          -1.0000e+00, -1.0000e+00]]])

In [12]:
unpacked.size()

torch.Size([7, 8, 6])

In [14]:
unpacked_out_len = torch.tensor([8,6,5,5,5,5,4])
unpacked_out_len

tensor([8, 6, 5, 5, 5, 5, 4])

In [28]:
unpacked.sum(1)

tensor([[-0.9247, -0.0499,  0.3421,  0.1070,  0.8217,  0.2058],
        [-3.6025, -3.1053, -2.7308, -2.8461, -2.2057, -2.7840],
        [-3.4467, -3.0859, -2.9509, -2.5809, -2.9469, -2.5737],
        [-3.2748, -3.0971, -2.5827, -2.7391, -2.3731, -2.8602],
        [-3.3687, -3.1568, -2.9034, -2.8213, -2.6452, -2.7464],
        [-3.9375, -3.2104, -2.6932, -2.8794, -2.3442, -2.6116],
        [-3.9375, -3.2104, -2.6932, -2.8794, -2.3442, -2.6116]])

In [29]:
unpacked.sum(1).size()

torch.Size([7, 6])

In [24]:
unpacked_out_len.unsqueeze(-1).size()

torch.Size([7, 1])

In [27]:
unpacked.sum(1) / unpacked_out_len.unsqueeze(-1).float()

tensor([[-0.1156, -0.0062,  0.0428,  0.0134,  0.1027,  0.0257],
        [-0.6004, -0.5175, -0.4551, -0.4743, -0.3676, -0.4640],
        [-0.6893, -0.6172, -0.5902, -0.5162, -0.5894, -0.5147],
        [-0.6550, -0.6194, -0.5165, -0.5478, -0.4746, -0.5720],
        [-0.6737, -0.6314, -0.5807, -0.5643, -0.5290, -0.5493],
        [-0.7875, -0.6421, -0.5386, -0.5759, -0.4688, -0.5223],
        [-0.9844, -0.8026, -0.6733, -0.7199, -0.5861, -0.6529]])

In [180]:
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence,pack_padded_sequence,pack_sequence,pad_packed_sequence


In [197]:
class MyData(Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

#def collate_fn(data):
#    data.sort(key=lambda x: len(x), reverse=True)
#    data = pad_sequence(data, batch_first=True, padding_value=0)
#    return data

def collate_fn(data):
    print(f'data pre-sort: {data}')
    data.sort(key=lambda x: len(x), reverse=True)
    print(f'data post-sort: {data}')
    seq_len = [s.size(0) for s in data] # Get the true length of the data
    print(f'seq_len: {seq_len}')
    data = pad_sequence(data, batch_first=True)    
    print(f'data pad_sequence: {data}')
    data = pack_padded_sequence(data, seq_len, batch_first=True)
    print(f'data pack_padded_sequence: {data}')
    return data


a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7])
c = torch.tensor([7,8])
d = torch.tensor([9])
train_x = [a, b, c, d]

data = MyData(train_x)
data_loader = DataLoader(data, batch_size=2, shuffle=True, collate_fn=collate_fn)
# Use the default collate_fn will report an error
#data_loader = DataLoader(data, batch_size=2, shuffle=True) 
batch_x = iter(data_loader).next()
batch_x

data pre-sort: [tensor([7, 8]), tensor([9])]
data post-sort: [tensor([7, 8]), tensor([9])]
seq_len: [2, 1]
data pad_sequence: tensor([[7, 8],
        [9, 0]])
data pack_padded_sequence: PackedSequence(data=tensor([7, 9, 8]), batch_sizes=tensor([2, 1]), sorted_indices=None, unsorted_indices=None)


PackedSequence(data=tensor([7, 9, 8]), batch_sizes=tensor([2, 1]), sorted_indices=None, unsorted_indices=None)

In [201]:
batch_x

PackedSequence(data=tensor([7, 9, 8]), batch_sizes=tensor([2, 1]), sorted_indices=None, unsorted_indices=None)

In [198]:
h0 = torch.rand(1, 2, 4).float()
c0 = torch.rand(1, 2, 4).float()

In [199]:
h0

tensor([[[0.7611, 0.8469, 0.3852, 0.3226],
         [0.4280, 0.8702, 0.8371, 0.9155]]])

In [202]:
rnn = nn.RNN(input_size=1, hidden_size=4, num_layers=1, batch_first=True) 
#h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))
rnn

RNN(1, 4, batch_first=True)

In [204]:
rnn = nn.RNN(input_size=4, hidden_size=4, num_layers=1, batch_first=True) 
#h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))
rnn

RNN(4, 4, batch_first=True)

In [209]:
batch_x

PackedSequence(data=tensor([7, 9, 8]), batch_sizes=tensor([2, 1]), sorted_indices=None, unsorted_indices=None)

In [206]:
h0

tensor([[[0.7611, 0.8469, 0.3852, 0.3226],
         [0.4280, 0.8702, 0.8371, 0.9155]]])

In [205]:
#forward 
out, h1 = rnn(batch_x, h0)
out

RuntimeError: input must have 2 dimensions, got 1

In [103]:
import torch

class MyData(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

def collate_fn(data):
    data.sort(key=lambda x: len(x), reverse=True)
    seq_len = [s.size(0) for s in data]
    data = torch.nn.utils.rnn.pad_sequence(data, batch_first=True).float()    
    print(f"data: {data}")
    data = data.unsqueeze(-1)
    print(f"data unsqueeze: {data}")
    data = torch.nn.utils.rnn.pack_padded_sequence(data, seq_len, batch_first=True)
    return data

a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7])
c = torch.tensor([7,8])
d = torch.tensor([9])
train_x = [a, b, c, d]

data = MyData(train_x)
data_loader = torch.utils.data.DataLoader(data, batch_size=2, shuffle=True, collate_fn=collate_fn)
batch_x = iter(data_loader).next()

data: tensor([[1., 2., 3., 4.],
        [5., 6., 7., 0.]])
data unsqueeze: tensor([[[1.],
         [2.],
         [3.],
         [4.]],

        [[5.],
         [6.],
         [7.],
         [0.]]])


In [104]:
batch_x

PackedSequence(data=tensor([[1.],
        [5.],
        [2.],
        [6.],
        [3.],
        [7.],
        [4.]]), batch_sizes=tensor([2, 2, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [105]:
rnn = torch.nn.LSTM(1, 4, 1, batch_first=True)
h0 = torch.rand(1, 2, 4).float()
c0 = torch.rand(1, 2, 4).float()

print(f"h0: {h0.size()}")
print(f"c0: {c0.size()}")
print(f"batch_x: {batch_x.data.size()}")

h0: torch.Size([1, 2, 4])
c0: torch.Size([1, 2, 4])
batch_x: torch.Size([7, 1])


In [76]:
out, (h1, c1) = rnn(batch_x, (h0, c0))

In [128]:
import torch

class MyData(torch.utils.data.Dataset):
    def __init__(self, data, labels):
        self.data = data
        self.labels = labels

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx], self.labels[idx]

#def collate_fn(data):
#    data.sort(key=lambda x: len(x), reverse=True)
#    seq_len = [s.size(0) for s in data]
#    #print(f"seq_len: {seq_len}")
#    data = torch.nn.utils.rnn.pad_sequence(data, batch_first=True).float()    
#    #print(f"data.size(): {data.size(1)}")
#    #print(f"data: {data}")
#    data = data.unsqueeze(-1)
#    #print(f"data unsqueeze: {data}")
#    data = torch.nn.utils.rnn.pack_padded_sequence(data, seq_len, batch_first=True)
#    return data

def collate_fn(data):
    data.sort(key=lambda x: len(x[0]), reverse=True)
    seq_len = [s[0].size(0) for s in data]

    data_list, label_list = [], []
    
    for (_data, _label) in data:
        data_list.append(_data)
        label_list.append(_label)

    data_list = torch.nn.utils.rnn.pad_sequence(data_list, batch_first=True, padding_value=-1).float() 
    #data_list = data_list.unsqueeze(-1)
    data_list = torch.nn.utils.rnn.pack_padded_sequence(data_list, seq_len, batch_first=True)

    return data_list, label_list


a = torch.tensor([[1,2,3], [2,4,3], [3,8,7], [4,6,5]])
b = torch.tensor([[1,5,7], [2,6,2], [3,9,10]])
c = torch.tensor([[1,64,33], [2,6,14]])
d = torch.tensor([[1,20,4]])
train_x = [a, b, c, d]
train_y = torch.tensor([[0, 1], [1, 0], [1, 0], [0, 1]])


data = MyData(train_x, train_y)
data_loader = torch.utils.data.DataLoader(data, batch_size=2, shuffle=True, collate_fn=collate_fn)
batch_x = iter(data_loader).next()

In [129]:
batch_x

(PackedSequence(data=tensor([[ 1.,  2.,  3.],
         [ 1.,  5.,  7.],
         [ 2.,  4.,  3.],
         [ 2.,  6.,  2.],
         [ 3.,  8.,  7.],
         [ 3.,  9., 10.],
         [ 4.,  6.,  5.]]), batch_sizes=tensor([2, 2, 2, 1]), sorted_indices=None, unsorted_indices=None),
 [tensor([0, 1]), tensor([1, 0])])

In [130]:
rnn = torch.nn.LSTM(3, 4, 1, batch_first=True)
h0 = torch.rand(1, 2, 4).float()
c0 = torch.rand(1, 2, 4).float()

print(f"h0: {h0.size()}")
print(f"c0: {c0.size()}")
print(f"batch_x: {batch_x[0].data.size()}")

h0: torch.Size([1, 2, 4])
c0: torch.Size([1, 2, 4])
batch_x: torch.Size([7, 3])


In [131]:
out, (h1, c1) = rnn(batch_x[0], (h0, c0))

In [132]:
out

PackedSequence(data=tensor([[ 1.9814e-01,  1.7159e-01, -2.6053e-04,  1.8220e-01],
        [ 3.6024e-03,  1.6864e-01,  2.1291e-05,  5.1185e-02],
        [ 1.0809e-01,  1.6072e-01, -7.2246e-04,  2.1089e-01],
        [ 3.7991e-02,  1.0185e-01, -3.0692e-04,  3.1341e-01],
        [ 2.8130e-02,  1.5002e-01, -1.2220e-06,  9.3069e-02],
        [ 2.6932e-03,  1.4218e-01, -5.3294e-08,  2.9613e-02],
        [ 2.1844e-02,  1.3494e-01, -1.5735e-05,  1.8890e-01]],
       grad_fn=<CatBackward0>), batch_sizes=tensor([2, 2, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [28]:
import torch 

prueba_1 = torch.tensor([[-7.5786,  7.4177],
        [ 2.0741, -2.0567],
        [ 2.1463, -1.9977],
        [ 1.7627, -1.3743],
        [-5.1376,  5.0417],
        [ 1.1576, -1.2956],
        [-5.2747,  5.0188],
        [-5.0353,  4.7304],
        [ 2.7630, -2.7475],
        [-3.8810,  3.9230]])

prueba_2 = torch.tensor([[32,  43],
        [ 14, 54],
        [ 64, 76],
        [ 76, 87],
        [-5.1376,  5.0417],
        [ 1.1576, -1.2956],
        [-5.2747,  5.0188],
        [-5.0353,  4.7304],
        [ 2.7630, -2.7475],
        [-3.8810,  3.9230]])

prueba_1

tensor([[-7.5786,  7.4177],
        [ 2.0741, -2.0567],
        [ 2.1463, -1.9977],
        [ 1.7627, -1.3743],
        [-5.1376,  5.0417],
        [ 1.1576, -1.2956],
        [-5.2747,  5.0188],
        [-5.0353,  4.7304],
        [ 2.7630, -2.7475],
        [-3.8810,  3.9230]])

In [29]:
torch.cat(([prueba_1, prueba_2]),dim=0)

tensor([[-7.5786,  7.4177],
        [ 2.0741, -2.0567],
        [ 2.1463, -1.9977],
        [ 1.7627, -1.3743],
        [-5.1376,  5.0417],
        [ 1.1576, -1.2956],
        [-5.2747,  5.0188],
        [-5.0353,  4.7304],
        [ 2.7630, -2.7475],
        [-3.8810,  3.9230],
        [32.0000, 43.0000],
        [14.0000, 54.0000],
        [64.0000, 76.0000],
        [76.0000, 87.0000],
        [-5.1376,  5.0417],
        [ 1.1576, -1.2956],
        [-5.2747,  5.0188],
        [-5.0353,  4.7304],
        [ 2.7630, -2.7475],
        [-3.8810,  3.9230]])

In [11]:
import math

math.exp(-7.5786) / (math.exp(-7.5786) + math.exp(7.4177))

3.0703616130270207e-07

In [31]:
torch.argmax(torch.softmax(torch.cat(([prueba_1, prueba_2]),dim=0), dim=0), axis=1)

tensor([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [24]:
torch.nn.functional.softmax(prueba, dim=0)

tensor([[1.2348e-05, 7.7962e-01],
        [1.9218e-01, 5.9869e-05],
        [2.0656e-01, 6.3508e-05],
        [1.4075e-01, 1.1846e-04],
        [1.4181e-04, 7.2444e-02],
        [7.6854e-02, 1.2816e-04],
        [1.2364e-04, 7.0803e-02],
        [1.5708e-04, 5.3064e-02],
        [3.8272e-01, 3.0005e-05],
        [4.9823e-04, 2.3668e-02]])

In [ ]:
torch.nn.functional.softmax(prueba, dim=0)[0]

In [22]:
torch.nn.functional.softmax(prueba, dim=1)

tensor([[3.0704e-07, 1.0000e+00],
        [9.8418e-01, 1.5816e-02],
        [9.8439e-01, 1.5612e-02],
        [9.5839e-01, 4.1607e-02],
        [3.7946e-05, 9.9996e-01],
        [9.2080e-01, 7.9205e-02],
        [3.3851e-05, 9.9997e-01],
        [5.7383e-05, 9.9994e-01],
        [9.9597e-01, 4.0278e-03],
        [4.0793e-04, 9.9959e-01]])

In [36]:
data_pre = [(torch.tensor([[2,6,8,35,6,8,98,56],
                           [2,6,8,35,6,8,98,56],
                           [2,6,8,35,6,8,98,56]]), torch.tensor([0., 1.])),
            (torch.tensor([[9,64,8,35,6,8,98,56],
                           [7,5,8,35,6,8,98,56],
                           [5,6,8,35,6,8,98,56],
                           [25,6,8,4,6,8,98,56],
                           [27,6,8,35,6,8,98,56],
                           [28,6,8,35,6,8,98,56],
                           [29,6,8,35,6,8,98,56]]), torch.tensor([1.,0.])),
            (torch.tensor([[0,6,8,35,6,8,98,56],
                           [1,66,8,35,6,8,98,56],
                           [6,36,8,35,6,8,98,56],
                           [8,45,8,35,6,8,98,56]]), torch.tensor([0.,1.]))
            ]
data_pre

[(tensor([[ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.])),
 (tensor([[ 9, 64,  8, 35,  6,  8, 98, 56],
          [ 7,  5,  8, 35,  6,  8, 98, 56],
          [ 5,  6,  8, 35,  6,  8, 98, 56],
          [25,  6,  8,  4,  6,  8, 98, 56],
          [27,  6,  8, 35,  6,  8, 98, 56],
          [28,  6,  8, 35,  6,  8, 98, 56],
          [29,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([1., 0.])),
 (tensor([[ 0,  6,  8, 35,  6,  8, 98, 56],
          [ 1, 66,  8, 35,  6,  8, 98, 56],
          [ 6, 36,  8, 35,  6,  8, 98, 56],
          [ 8, 45,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.]))]

In [37]:
list_lenght = torch.zeros(len(data_pre))
for i in range(len(data_pre)):
    list_lenght[i] = len(data_pre[i][0])

list_lenght

tensor([3., 7., 4.])

In [38]:
idx_sorted = list_lenght.argsort(descending=True)
idx_sorted

tensor([1, 2, 0])

In [46]:
seq = list_lenght[idx_sorted]
seq

tensor([7., 4., 3.])

In [57]:
dataset_sorted = []

for idx in idx_sorted:
    dataset_sorted.append(data_pre[idx])

dataset_sorted

[(tensor([[ 9, 64,  8, 35,  6,  8, 98, 56],
          [ 7,  5,  8, 35,  6,  8, 98, 56],
          [ 5,  6,  8, 35,  6,  8, 98, 56],
          [25,  6,  8,  4,  6,  8, 98, 56],
          [27,  6,  8, 35,  6,  8, 98, 56],
          [28,  6,  8, 35,  6,  8, 98, 56],
          [29,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([1., 0.])),
 (tensor([[ 0,  6,  8, 35,  6,  8, 98, 56],
          [ 1, 66,  8, 35,  6,  8, 98, 56],
          [ 6, 36,  8, 35,  6,  8, 98, 56],
          [ 8, 45,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.])),
 (tensor([[ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.]))]

In [62]:
scores = torch.tensor([[-7.4802,  7.7346],
        [ 1.7185, -1.9739],
        [ 0.7562, -0.8994]])

scores

tensor([[-7.4802,  7.7346],
        [ 1.7185, -1.9739],
        [ 0.7562, -0.8994]])

In [63]:
idx_torch = torch.tensor([1, 2, 0])
idx_torch

tensor([1, 2, 0])

In [64]:
scores = scores[idx_sorted]
scores

tensor([[ 1.7185, -1.9739],
        [ 0.7562, -0.8994],
        [-7.4802,  7.7346]])

In [65]:
torch.zeros(size=scores.size())

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [66]:
scores_original = torch.zeros(size=scores.size())
for i in range(len(idx_sorted)):
    scores_original[idx_sorted[i]] = scores[i]

scores_original

tensor([[-7.4802,  7.7346],
        [ 1.7185, -1.9739],
        [ 0.7562, -0.8994]])

In [52]:
y_train = torch.tensor([[0., 1.],
        [1., 0.],
        [0., 1.]]).to('cuda')

y_train

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]], device='cuda:0')

In [53]:
y_train[idx_sorted]

tensor([[1., 0.],
        [0., 1.],
        [0., 1.]], device='cuda:0')

In [23]:
torch.index_select(scores, 0, idx_torch)

tensor([[ 1.7185, -1.9739],
        [ 0.7562, -0.8994],
        [-7.4802,  7.7346]])

In [10]:
idx_sorted

array([1, 2, 0], dtype=int64)

In [16]:
scores[idx_sorted]

ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

In [95]:
idx_sorted

array([1, 2, 0], dtype=int64)

In [94]:
scores[idx_sorted]

ValueError: At least one stride in the given numpy array is negative, and tensors with negative strides are not currently supported. (You can probably work around this by making a copy of your array  with array.copy().) 

In [74]:
data_pre[idx_sorted]

TypeError: only integer scalar arrays can be converted to a scalar index

In [47]:
range(len(data_pre))

range(0, 3)

In [46]:
sorted(range(len(data_pre)), key=lambda k: data_pre[0][k])

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

In [1]:
import torch

labels = torch.tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])
labels

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])

In [34]:
len(data_pre[0][0])

3

In [23]:
import numpy as np

data_pre_np = np.array(data_pre, dtype=object) 

C:\Users\damor\AppData\Local\Temp/ipykernel_24224/3768877712.py:3: FutureWarning: The input object of type 'Tensor' is an array-like implementing one of the corresponding protocols (`__array__`, `__array_interface__` or `__array_struct__`); but not a sequence (or 0-D). In the future, this object will be coerced as if it was first converted using `np.array(obj)`. To retain the old behaviour, you have to either modify the type 'Tensor', or assign to an empty array created with `np.empty(correct_shape, dtype=object)`.
  data_pre_np = np.array(data_pre, dtype=object)


In [28]:
torch.argsort(key=lambda data_pre: len(data_pre[0]), dim=1)

TypeError: argsort() received an invalid combination of arguments - got (key=function, dim=int, ), but expected one of:
 * (Tensor input, int dim, bool descending)
 * (Tensor input, name dim, bool descending)


In [30]:
lambda data_pre: len(data_pre[0])

TypeError: 'function' object is not iterable

In [ ]:
key=lambda x: len(x[0])

In [24]:
data_pre_np.argsort(key=lambda x: len(x[0]), reverse=True)

TypeError: 'key' is an invalid keyword argument for argsort()

In [13]:
data_pre_np

[(tensor([[ 9, 64,  8, 35,  6,  8, 98, 56],
          [ 7,  5,  8, 35,  6,  8, 98, 56],
          [ 5,  6,  8, 35,  6,  8, 98, 56],
          [25,  6,  8,  4,  6,  8, 98, 56],
          [27,  6,  8, 35,  6,  8, 98, 56],
          [28,  6,  8, 35,  6,  8, 98, 56],
          [29,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([1., 0.])),
 (tensor([[ 0,  6,  8, 35,  6,  8, 98, 56],
          [ 1, 66,  8, 35,  6,  8, 98, 56],
          [ 6, 36,  8, 35,  6,  8, 98, 56],
          [ 8, 45,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.])),
 (tensor([[ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56],
          [ 2,  6,  8, 35,  6,  8, 98, 56]]),
  tensor([0., 1.]))]